// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	strictgin "github.com/oapi-codegen/runtime/strictmiddleware/gin"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /api/chats)
	ChatServiceCreateChatRoom(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// ChatServiceCreateChatRoom operation middleware
func (siw *ServerInterfaceWrapper) ChatServiceCreateChatRoom(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ChatServiceCreateChatRoom(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/api/chats", wrapper.ChatServiceCreateChatRoom)
}

type ChatServiceCreateChatRoomRequestObject struct {
	Body *ChatServiceCreateChatRoomJSONRequestBody
}

type ChatServiceCreateChatRoomResponseObject interface {
	VisitChatServiceCreateChatRoomResponse(w http.ResponseWriter) error
}

type ChatServiceCreateChatRoom200JSONResponse CreateChatRoomResponse

func (response ChatServiceCreateChatRoom200JSONResponse) VisitChatServiceCreateChatRoomResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ChatServiceCreateChatRoomdefaultJSONResponse struct {
	Body       Status
	StatusCode int
}

func (response ChatServiceCreateChatRoomdefaultJSONResponse) VisitChatServiceCreateChatRoomResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (POST /api/chats)
	ChatServiceCreateChatRoom(ctx context.Context, request ChatServiceCreateChatRoomRequestObject) (ChatServiceCreateChatRoomResponseObject, error)
}

type StrictHandlerFunc = strictgin.StrictGinHandlerFunc
type StrictMiddlewareFunc = strictgin.StrictGinMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// ChatServiceCreateChatRoom operation middleware
func (sh *strictHandler) ChatServiceCreateChatRoom(ctx *gin.Context) {
	var request ChatServiceCreateChatRoomRequestObject

	var body ChatServiceCreateChatRoomJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ChatServiceCreateChatRoom(ctx, request.(ChatServiceCreateChatRoomRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ChatServiceCreateChatRoom")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(ChatServiceCreateChatRoomResponseObject); ok {
		if err := validResponse.VisitChatServiceCreateChatRoomResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7RWQW8bNxP9KwN+36EBlJWS9FKdoiiBa/RQwfalMARklpzdnYRLbshZGaqh/16Qu7Ik",
	"S619aG/LITnz5s0bzj4q7dvOO3IS1fxRRd1Qi/lz2aDceN+m7y74joIw5R0dCIXMQtKi8qFFUXNlUOit",
	"cEtqomTbkZqrKIFdrXYTxSadPTM7bOnCxm6iAv3oOZBR8/vh1PrJqy+/kZZ0fZmB7IHe0I+eopzj/fso",
	"L3qMnXeRLlBwRM7/A1Vqrv43PVA5HXmcPpF4MdqV97WlVfDiy75auG1yh8awsHdoV0chJfQ0UYaiDtyl",
	"bTVXS+8E2UVABxhKloBhC5ECo+U/yUBLMWJNgNa7Gh5YGkD4mGCANCgwuCspgjQE2e6r/H3upFCTZxx8",
	"HPJ5fIbq7lWuXlGLW0Hp4+UAX4fNr0MkQxU7ioBgfc0aLVAIPkDrDdkhVY4QexYsLUHlAxiuKgrkBLrg",
	"64Bty64GchsO3rWphhNgp21vkv3my+0dLFbXiWoDN6tlXhRwnR33kQyUW7ivb1bL9U+NSBfn02nN0vRl",
	"oX07rUOn3xTwBXVzgL6vjt6XUZpABB2TppjYMyg4H1PR3tBkn9ZwcZLBDCZDgmxjAX/4HjQ6qNgZ8L1A",
	"6wMBlulTGo4nzKT7jX8A8fDgw/dBISzALlfufrG6hs8UuXZw1bOhQ27a+t4UddZvzhA7jlOTz05ziPjm",
	"XDEpicv1jJmTMcuHhnUDsfG9NVBSkje5voUN2j7L6n4MHDpdLL2h9ZkhxX56mdjJh/cHzbETqikkiY20",
	"nWNagOUoKdZIdhxkpDGEbSbnGe9w11CgpAYE7dvWO4h07CArNWbtZSGJT7pJOFmojS89JOdPxaFlMATM",
	"6zHUpXQMbcimWrytUGepn0rpOefs4IurLcemgIXbJqyXrx7dsV6PjZ6EFVNz7ZV0VJ9B/sXI3PoftqBi",
	"smYCPhy5Lgf6tWVy8qqXJJnYVX5QoBPUeUZQi2wTe9Kgw8j4y8/vZh/rZE2KVvvppK7Iu2bbf4frNpPO",
	"YpP5k8WypPD2V95QKqmaqA2FOBA+K2bFu3Tad+SwYzVXH4pZ8SG1BEqTy516ZpoGSV51fhhdqUaYynZt",
	"0hPfoNxS2LCm09GkhhFJUT55s92nRi77wK6zrLOX6beYAO0n+4vz6uJE3Z1O5DSLsmGYjhn++9nsPwMx",
	"DuGM4lTXv/82dHGFvZV/Lf44eC7E+zxEGjsgHJBNlGAd08/KUcXUene0s/8POTmxW+/+CgAA//+qMLc/",
	"gwkAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
