// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	strictgin "github.com/oapi-codegen/runtime/strictmiddleware/gin"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /api/chats)
	ChatServiceCreateChatRoom(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// ChatServiceCreateChatRoom operation middleware
func (siw *ServerInterfaceWrapper) ChatServiceCreateChatRoom(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ChatServiceCreateChatRoom(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/api/chats", wrapper.ChatServiceCreateChatRoom)
}

type ChatServiceCreateChatRoomRequestObject struct {
	Body *ChatServiceCreateChatRoomJSONRequestBody
}

type ChatServiceCreateChatRoomResponseObject interface {
	VisitChatServiceCreateChatRoomResponse(w http.ResponseWriter) error
}

type ChatServiceCreateChatRoom200JSONResponse CreateChatRoomResponse

func (response ChatServiceCreateChatRoom200JSONResponse) VisitChatServiceCreateChatRoomResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ChatServiceCreateChatRoomdefaultJSONResponse struct {
	Body       Status
	StatusCode int
}

func (response ChatServiceCreateChatRoomdefaultJSONResponse) VisitChatServiceCreateChatRoomResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (POST /api/chats)
	ChatServiceCreateChatRoom(ctx context.Context, request ChatServiceCreateChatRoomRequestObject) (ChatServiceCreateChatRoomResponseObject, error)
}

type StrictHandlerFunc = strictgin.StrictGinHandlerFunc
type StrictMiddlewareFunc = strictgin.StrictGinMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// ChatServiceCreateChatRoom operation middleware
func (sh *strictHandler) ChatServiceCreateChatRoom(ctx *gin.Context) {
	var request ChatServiceCreateChatRoomRequestObject

	var body ChatServiceCreateChatRoomJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ChatServiceCreateChatRoom(ctx, request.(ChatServiceCreateChatRoomRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ChatServiceCreateChatRoom")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(ChatServiceCreateChatRoomResponseObject); ok {
		if err := validResponse.VisitChatServiceCreateChatRoomResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7RWT2/buBP9KgP+foctoMrZ5uZTvW5QBHtYI8llERgoRY6k6VIclRwl8Ab+7gtScmxH",
	"xraH7k38N+/Nm0eOXpThrmePXqJavqhoWux0/ly3Wu6Yu/TdB+4xCGFeMQG1oF1JGtQcOi1qqawWfC/U",
	"oSqU7HpUSxUlkG/UvlBk097ZtNcdXljYFyrgt4ECWrV8HHdtX6Ny9RWNpOPrTORA9A6/DRhlzvcno8Se",
	"fcQLspwI9v+AtVqq/y2O8i4mbRevwiYGM7TPzI3DTWDhaqhXfpfCaWtJiL12mxNICQMWymI0gfq0rJZq",
	"zV40+Qjagw4VSdBhBxEDaUd/o4UOY9QNgnbsG3gmaUHDx0QDpNUCY7gKI0iLkOe5zt/zIKUq3mjwcczn",
	"5Q2rhx8KNa/PTJ170TLEywBfxsUvI5LFmjxG0OC4IaMdYAgcoGOLbkyVIsSBRFcOoeYAluoaA3qBPnAT",
	"dNeRbwD9EwX2XaphAeSNG2yav7u5f4DV5jZJbeFus86DEm5z4CGihWoHj83dZr39pRXp43KxaEjaoSoN",
	"d4sm9OZdCTfatEfqh+qYQxmlDYjQExqMST2rRS+nVAxbLA5pjQeLTGacsiiaXCzhTx7AaA81eQs8CHQc",
	"EHSVPqWleKZMOt/yMwjDM4e/RoeQAPlcucfV5hY+YaTGw+eBLB5zM44HWzbZvzlD3VNc2Lx3kSHiu7lj",
	"UhKX6xmzJlOWzy2ZFmLLg7NQYbI3+qGDJ+2GbKvHCTj0plyzxe1sImG/vlbk5frD0XPkBRsMyWKTbHNO",
	"K3AUJWFNYsfRRkaHsMvivNEdHloMmNygwXDXsYeIpwGyU2P2XjaScPJN4kmCXfzeQzJ/Ko5XRoeg83iC",
	"upSOxSd0qRbva22y1c+t9FZz8nDjG0exLWHld4nr5aMnZxyb6aInY8V0uQ5OOqnPaP9yUm77L0tQEzpb",
	"AIeT0NUov3GEXn7oJUlT5GvObYHEpbX0Lt9jeCKDqRyqUE8Y4ijWVXlV/prk5B697kkt1XV5VV4nO2tp",
	"c6mS3xepCeRRz2MrSvrqJPmtPcc4bytqbEYY5Te2u/FieEGfY+i+d2RylMXXmAgdOvV3e83FDrk/732p",
	"j+SJsbNl+h+urv4zElMDzSzOPfnH7+MNrPXg5KfhT03jAt6nEWlybzgyK5ToJqbfgpOKqe3+ZOXwX3G2",
	"Y7/d/xMAAP//Y0EsiFMJAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
