---
apiVersion: v1
kind: Service
metadata:
  name: postgres-db
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: redis-cache
spec:
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: broker-kafka
spec:
  selector:
    app: broker
  ports:
    - port: 9092
      targetPort: 9092
  type: LoadBalancer
