apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-broker-pv
spec:
  capacity:
    storage: 1Gi # Adjust the storage size as needed
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hostpath
  hostPath:
    path: /media/mint/linux-1/k8s/kafka # Adjust the path to match your Kafka data directory on the host
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: broker
  name: kafka-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: kafka-broker-pv
  storageClassName: hostpath
