apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.33.0 (HEAD)
  labels:
    io.kompose.service: blabber-hive
  name: blabber-hive
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: blabber-hive
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.33.0 (HEAD)
      labels:
        io.kompose.network/blabber-hive-blabber-hive: "true"
        io.kompose.service: blabber-hive
    spec:
      containers:
        - env:
            - name: BULK_INSERT_SIZE
              valueFrom:
                configMapKeyRef:
                  key: BULK_INSERT_SIZE
                  name: blabber-hive-env-docker
            - name: BULK_INSERT_TIME
              valueFrom:
                configMapKeyRef:
                  key: BULK_INSERT_TIME
                  name: blabber-hive-env-docker
            - name: JWT_SECRET
              valueFrom:
                configMapKeyRef:
                  key: JWT_SECRET
                  name: blabber-hive-env-docker
            - name: KAFKA_BROKER_URL
              valueFrom:
                configMapKeyRef:
                  key: KAFKA_BROKER_URL
                  name: blabber-hive-env-docker
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_HOST
                  name: blabber-hive-env-docker
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PASSWORD
                  name: blabber-hive-env-docker
            - name: POSTGRES_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_USERNAME
                  name: blabber-hive-env-docker
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  key: REDIS_URL
                  name: blabber-hive-env-docker
            - name: SUPABASE_AUTH
              valueFrom:
                configMapKeyRef:
                  key: SUPABASE_AUTH
                  name: blabber-hive-env-docker
            - name: SUPABASE_DOMAIN
              valueFrom:
                configMapKeyRef:
                  key: SUPABASE_DOMAIN
                  name: blabber-hive-env-docker
            - name: SUPABASE_POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: SUPABASE_POSTGRES_PASSWORD
                  name: blabber-hive-env-docker
            - name: SUPABASE_SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  key: SUPABASE_SECRET_KEY
                  name: blabber-hive-env-docker
            - name: TZ
              value: Asia/Seoul
          image: blabber-hive:v1
          name: blabber-hive
          ports:
            - containerPort: 8080

              protocol: TCP
      restartPolicy: Always
