// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// File: internal/pkg/sqlc/queries.sql
	// CreateChatRoom.sql
	CreateChatRoom(ctx context.Context, arg CreateChatRoomParams) error
	// FindChatRoomByID.sql
	FindChatRoomByID(ctx context.Context, id uuid.UUID) (FindChatRoomByIDRow, error)
	// FindChatRoomInfoByID.sql
	FindChatRoomInfoByID(ctx context.Context, id uuid.UUID) ([]FindChatRoomInfoByIDRow, error)
	// FindChatRoomList.sql
	FindChatRoomList(ctx context.Context) ([]FindChatRoomListRow, error)
	// GetFirstPageMessages.sql
	GetFirstPageMessages(ctx context.Context, arg GetFirstPageMessagesParams) ([]GetFirstPageMessagesRow, error)
	// GetPaginatedMessages.sql
	GetPaginatedMessages(ctx context.Context, arg GetPaginatedMessagesParams) ([]GetPaginatedMessagesRow, error)
	// JoinChatRoomByID.sql
	JoinChatRoomByID(ctx context.Context, arg JoinChatRoomByIDParams) error
}

var _ Querier = (*Queries)(nil)
