---
apiVersion: v1
kind: Service
metadata:
  name: postgres-nodeport
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 32222
  selector:
    app: blabber-hive
    tier: postgres
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.33.0 (HEAD)
  labels:
    app: blabber-hive
    tier: postgres
    io.kompose.service: postgres
  name: postgres
spec:
  ports:
    - port: 5432
  selector:
    io.kompose.network/blabber-hive-blabber-hive: "true"
    io.kompose.service: postgres
  # Do not use this  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.33.0 (HEAD)
  labels:
    io.kompose.service: postgres
  name: postgres
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postgres
      app: blabber-hive
      tier: postgres
  #  strategy: # Not need to specify the strategy for StatefulSet
  #    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.33.0 (HEAD)
      labels:
        io.kompose.network/blabber-hive-blabber-hive: "true"
        io.kompose.service: postgres
        app: blabber-hive
        tier: postgres
    spec:
      containers:
        - env:
            - name: BULK_INSERT_SIZE
              valueFrom:
                configMapKeyRef:
                  key: BULK_INSERT_SIZE
                  name: postgres-env-docker
            - name: BULK_INSERT_TIME
              valueFrom:
                configMapKeyRef:
                  key: BULK_INSERT_TIME
                  name: postgres-env-docker
            - name: JWT_SECRET
              valueFrom:
                configMapKeyRef:
                  key: JWT_SECRET
                  name: postgres-env-docker
            - name: KAFKA_BROKER_URL
              valueFrom:
                configMapKeyRef:
                  key: KAFKA_BROKER_URL
                  name: postgres-env-docker
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_HOST
                  name: postgres-env-docker
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PASSWORD
                  name: postgres-env-docker
            - name: POSTGRES_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_USERNAME
                  name: postgres-env-docker
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  key: REDIS_URL
                  name: postgres-env-docker
            - name: SUPABASE_AUTH
              valueFrom:
                configMapKeyRef:
                  key: SUPABASE_AUTH
                  name: postgres-env-docker
            - name: SUPABASE_DOMAIN
              valueFrom:
                configMapKeyRef:
                  key: SUPABASE_DOMAIN
                  name: postgres-env-docker
            - name: SUPABASE_POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: SUPABASE_POSTGRES_PASSWORD
                  name: postgres-env-docker
            - name: SUPABASE_SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  key: SUPABASE_SECRET_KEY
                  name: postgres-env-docker
          image: postgres:15.5-alpine
          name: blabber-hive-postgres
          ports:
            - containerPort: 5432
              hostPort: 5432
              protocol: TCP
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          hostPath:
            path: /home/geonhyuk/Documents/CS/Projects/blabber-hive/database
