apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.33.0 (HEAD)
  labels:
    io.kompose.service: grafana
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: grafana
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.33.0 (HEAD)
      labels:
        io.kompose.network/blabber-hive-blabber-hive: "true"
        io.kompose.service: grafana
    spec:
      containers:
        - image: grafana/grafana
          name: blabber-hive-grafana
          ports:
            - containerPort: 3000
              hostPort: 3001
              protocol: TCP
      restartPolicy: Always
