name: Fly.io integration
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Code
        uses: actions/checkout@v3

      - name: Set up flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Build Docker Image
        run: cd backend && docker build -t blabber-hive:v1 -f Dockerfile.multistage .
      - name: Deploy to Fly.io
        run: flyctl deploy --app $FLY_APP_NAME --config backend/fly.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          FLY_APP_NAME: blabber-hive
